=== madrider/prasad/BASE.XSD
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="EMP">
	<xs:complexType>
		<xs:sequence>
		<xs:element name="note" maxOccurs="unbounded">
			<xs:complexType>
			
			<xs:all>
			<xs:element name="EMPN" type="xs:integer"/>
			<xs:element name="ENAME" type="xs:string"/>
			<xs:element name="JOB" type="xs:string"/>
			<xs:element name="MGR" type="xs:string"/>
			<xs:element name="HIREDATE" type="xs:string"/>
			<xs:element name="SAL" type="xs:string"/>
			<xs:element name="COMM" type="xs:string"/>
			<xs:element name="DEPTNO" type="xs:string"/>
			</xs:all>
			</xs:complexType>
			
		</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== madrider/prasad/employee details.xml
<?xml version="1.0"?>
<EMP xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="BASE.XSD">
	<note>
		<EMPN>7369</EMPN>
		<ENAME>SMITH</ENAME>
		<JOB>CLERK</JOB>
		<MGR>7902</MGR>
		<HIREDATE>17-DEC-80</HIREDATE>
		<SAL>1100</SAL>
		<COMM>200</COMM>
		<DEPTNO>20</DEPTNO>
		</note>
		<note>
		<EMPN>7499</EMPN>
		<ENAME>ALLEN</ENAME>
		<JOB>SALESMAN</JOB>
		<MGR>7698</MGR>
		<HIREDATE>20-FEB-81</HIREDATE>
		<SAL>1600</SAL>
		<COMM>24820</COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>7521</EMPN>
		<ENAME>WARD</ENAME>
		<JOB>SALESMAN</JOB>
		<MGR>7698</MGR>
		<HIREDATE>22-FEB-81</HIREDATE>
		<SAL>1375</SAL>
		<COMM>19700</COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>7566</EMPN>
		<ENAME>JONES</ENAME>
		<JOB>MANAGER</JOB>
		<MGR>7839</MGR>
		<HIREDATE>02-APR-81</HIREDATE>
		<SAL>3175</SAL>
		<COMM></COMM>
		<DEPTNO>20</DEPTNO>
		</note>
		<note>
		<EMPN>7654</EMPN>
		<ENAME>MARTIN</ENAME>
		<JOB>SALESMAN</JOB>
		<MGR>7698</MGR>
		<HIREDATE>28-SEP-81</HIREDATE>
		<SAL>1375</SAL>
		<COMM>20600</COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>7698</EMPN>
		<ENAME>BLAK</ENAME>
		<JOB>MANAGER</JOB>
		<MGR>7839</MGR>
		<HIREDATE>01-MAY-81</HIREDATE>
		<SAL>2850</SAL>
		<COMM></COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>7782</EMPN>
		<ENAME>CLARK</ENAME>
		<JOB>MANAGER</JOB>
		<MGR>7839</MGR>
		<HIREDATE>09-JUN-81</HIREDATE>
		<SAL>2450</SAL>
		<COMM></COMM>
		<DEPTNO>10</DEPTNO>
		</note>
		<note>
		<EMPN>7788</EMPN>
		<ENAME>SCOTT</ENAME>
		<JOB>ANALYST</JOB>
		<MGR>7566</MGR>
		<HIREDATE>19-APR-87</HIREDATE>
		<SAL>2000</SAL>
		<COMM></COMM>
		<DEPTNO>20</DEPTNO>
		</note>
		<note>
		<EMPN>7839</EMPN>
		<ENAME>KING</ENAME>
		<JOB>PRESEDENT</JOB>
		<MGR></MGR>
		<HIREDATE>17-NOV-81</HIREDATE>
		<SAL>5000</SAL>
		<COMM></COMM>
		<DEPTNO>10</DEPTNO>
		</note>
		<note>
		<EMPN>7844</EMPN>
		<ENAME>TURNER</ENAME>
		<JOB>SALESMAN</JOB>
		<MGR>7698</MGR>
		<HIREDATE>08-SEP-81</HIREDATE>
		<SAL>1650</SAL>
		<COMM>23000</COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>876</EMPN>
		<ENAME>AFDEMS</ENAME>
		<JOB>CLERK</JOB>
		<MGR>7788</MGR>
		<HIREDATE>23-MAY-87</HIREDATE>
		<SAL>1430</SAL>
		<COMM>200</COMM>
		<DEPTNO>20</DEPTNO>
		</note>
		<note>
		<EMPN>7900</EMPN>
		<ENAME>JAMES</ENAME>
		<JOB>CLERK</JOB>
		<MGR>7698</MGR>
		<HIREDATE>03-DEC-81</HIREDATE>
		<SAL>1045</SAL>
		<COMM>200</COMM>
		<DEPTNO>30</DEPTNO>
		</note>
		<note>
		<EMPN>7902</EMPN>
		<ENAME>FORD</ENAME>
		<JOB>ANALYTS</JOB>
		<MGR>7566</MGR>
		<HIREDATE>03-DEC-81</HIREDATE>
		<SAL>3200</SAL>
		<COMM></COMM>
		<DEPTNO>20</DEPTNO>
		</note>
		<note>
		<EMPN>7934</EMPN>
		<ENAME>MILLER</ENAME>
		<JOB>CLERK</JOB>
		<MGR>7782</MGR>
		<HIREDATE>23-JAN-82</HIREDATE>
		<SAL>1430</SAL>
		<COMM>200</COMM>
		<DEPTNO>10</DEPTNO>
	</note>
</EMP>
